name: Publish Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/deel-web-app"
          COMMIT_SHA=$(echo ${GITHUB_SHA::7})
          TAG="${IMAGE_NAME}:${COMMIT_SHA}"
          docker buildx build --push --tag $TAG .
          docker tag $TAG "${IMAGE_NAME}:latest"
          docker push $TAG
          docker push "${IMAGE_NAME}:latest"
